---
applications:
- name: t2m
  memory: 64M
  disk_quota: 50M
  instances: 10
  docker:
    image: docker.io/frnksgr/t2m:alpine3.11
  health-check-type: http
  health-check-http-endpoint: /healthz
  routes:
  - route: t2m.priv.c4k.k8s.cf.frnksgr.net
  - route: t2m.pub.c4k.k8s.cf.frnksgr.net
  env:
    TARGET_URL: "http://t2m.priv.c4k.k8s.cf.frnksgr.net"
